# Generated by Django 4.0.7 on 2022-10-09 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productapp', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('guest_user', models.CharField(blank=True, max_length=200, null=True)),
                ('cancel_status', models.BooleanField(blank=True, default=False, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productapp.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderd', models.BooleanField(default=False)),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Returned', 'Returned')], default='Confirmed', max_length=100)),
                ('transcation_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('date_delivered', models.DateField(default='2022-01-01')),
                ('guest_user', models.CharField(blank=True, max_length=200, null=True)),
                ('returnexpiry', models.BooleanField(blank=True, default=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('discount', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customeradress')),
                ('items', models.ManyToManyField(blank=True, to='cartapp.cartitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
